# Generated by Django 4.1.7 on 2023-06-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='term_of_use_privasy_ploicy',
            field=models.BooleanField(),
        ),
    ]
