# Generated by Django 4.1.7 on 2023-03-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadownload', '0002_plotfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotfile',
            name='plot',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='PlotFile'),
        ),
    ]
