# Generated by Django 4.1.7 on 2023-03-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datadownload', '0003_alter_plotfile_plot'),
    ]

    operations = [
    ]
