# Generated by Django 4.1.7 on 2023-03-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datadownload', '0004_auto_20230307_1833'),
    ]

    operations = [
    ]
