# Generated by Django 4.1.7 on 2023-03-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datadownload', '0005_auto_20230307_2000'),
    ]

    operations = [
    ]
