# Generated by Django 4.1.7 on 2023-06-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadownload', '0007_alter_plotfile_plot_controlplotfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotfile',
            name='plot_hazard12m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plotfile',
            name='plot_hazard3m',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plotfile',
            name='plot_hazard6m',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
