# Generated by Django 4.1.7 on 2023-06-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadownload', '0009_plotfile_plot_avr_surv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotfile',
            name='plot_avr_surv',
            field=models.CharField(max_length=50),
        ),
    ]
